### ISSUE TITLE
[meta] Application.* API will be removed

### ISSUE THREAD

**Issue by Infocatcher** [Infocatcher/Custom_Buttons#36]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1090880

- [ ] Bookmarks Folder
<br>`Application.prefs.getValue()`/`setValue()`
<br>`Application.name`
- [ ] Custom Buttons Editor: Toggle on Top
<br>`Application.storage.get()`/`set()`
- [ ] Source Editor
<br>`Application.storage.get()`/`set()`
- [ ] Cookies Permissions
<br>`Application.storage.get()`/`set()`
- [ ] Extensions Developer Tools
<br>`Application.restart()`
<br>`Application.quit()`
- [ ] Extensions Installer
<br>`Application.restart()`
- [ ] Toggle Flash
<br>`Application.prefs.getValue()`
- [ ] Toggle Restartless Add-ons
<br>`Application.prefs.getValue()`
